### ISSUE TITLE
IntegratedML bug in 2022.3 build 599

### ISSUE THREAD

**Issue by psteiwer** [intersystems-community/zpm-dockerhub#26]
intersystemsdc/iris-ml-community:2022.3.0.599.0-zpm is built on top of an unreleased build (599). The official community edition build for 2022.3 is 606. If users try and use the 2022.3.0.599.0-zpm tag, they will see this error. It does appear that latest now points to latest: 2022.3.0.606.0, which is good and should allow users to get the correct base build. However, does it make sense to remove the 599 build so that users do not get errors when trying to use it?

For context, if you try and train a model on the 599 build, you see this error:
 [SQLCODE: <-400>:<Fatal error occurred>]

  [%msg: <ERROR #5002: ObjectScript error: %OnInit+20^%ML.AutoML.Provider.1^1^ *<class 'pkg_resources.extern.packaging.version.InvalidVersion'>: Invalid version: '1.1build1' - Import>]

**Comment by psteiwer** [comment]
Correction:
.github/workflows/main.yml has been modified to be "latest: 2022.3.0.606.0". However, at this time, intersystemsdc/iris-ml-community:latest is still using 2022.2.0.368.0

**Comment by daimor** [comment]
Should be ok now

**Comment by evshvarov** [comment]
@psteiwer, closing it
