### ISSUE TITLE
var env with "_" underscore

### ISSUE THREAD

**Issue by grongierisc** [intersystems-community/zpm-dockerhub#29]
why using an underscore ? IRISUSERNAME and IRISPASSWORD are env used by embedded python, using "_" underscore can add confusion

**Comment by daimor** [comment]
I've used that way in irissqlcli, thought to make some universal, did not know about embedded python way is different
why they did this strange way

**Comment by grongierisc** [comment]
I agree with "_" is more readable, but i guess it's easier to adapt iris DC version than embedded python

**Comment by daimor** [comment]
I'll add it

**Comment by daimor** [comment]
I don't see that embedded python would use `IRISUSERNAME` and `IRISPASSWORD`, it always enters as irisowner

**Comment by grongierisc** [comment]
It's because you may have enable `%Service_CallIn`with `Operating System`

In this case, IRIS try first `Operating System` then `Password`

<img width="632" alt="image" src="https://user-images.githubusercontent.com/47849411/231411678-3d7ebb57-2990-4ff5-bad8-22c0d616209f.png">

**Comment by daimor** [comment]
I've just enabled service, and did not touch methods

**Comment by grongierisc** [comment]
By default it's `Operating System`+ `Password`
